package net.templefox.database.data;

// Generated 2013-8-21 19:58:16 by Hibernate Tools 3.4.0.CR1

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import org.json.JSONException;
import org.json.JSONObject;

import android.annotation.SuppressLint;
import android.content.ContentValues;
import android.util.Log;

/**
 * Comment generated by hbm2java
 */
@SuppressLint("SimpleDateFormat")
public class Comment extends Entity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6225609792902914062L;
	private Integer id;
	private Integer activityID;
	private User user;
	private String content;
	private Date datatime;
	private String pictureUrl;

	public Comment() {
	}

	public Comment(Date datatime) {
		this.datatime = datatime;
	}

	public Comment(Integer activity, User user, String content, Date datatime,
			String pictureUrl) {
		this.activityID = activity;
		this.user = user;
		this.content = content;
		this.datatime = datatime;
		this.pictureUrl = pictureUrl;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getActivityID() {
		return this.activityID;
	}

	public void setActivityID(Integer activity) {
		this.activityID = activity;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getDatatime() {
		return this.datatime;
	}

	public void setDatatime(Date datatime) {
		this.datatime = datatime;
	}

	public String getPictureUrl() {
		return this.pictureUrl;
	}

	public void setPictureUrl(String pictureUrl) {
		this.pictureUrl = pictureUrl;
	}

	@Override
	protected ContentValues getContentValues() {
		ContentValues contentValues = new ContentValues();
		contentValues.put("id", id);
		contentValues.put("content", content);
		contentValues.put("ActivityID", activityID);
		try {
			contentValues.put("datetime", new SimpleDateFormat(
					"yyyy-MM-dd HH:mm:ss").format(datatime));
		} catch (NullPointerException e) {
			Log.e("CP Error", e.getMessage());
			Log.w("CP Exception", Log.getStackTraceString(e));
		} catch (IllegalArgumentException e) {
			Log.e("CP Error", e.getMessage());
			Log.w("CP Exception", Log.getStackTraceString(e));
		}
		contentValues.put("picture_url", pictureUrl);
		return contentValues;
	}

	@Override
	protected String getTableName() {
		return "comment";
	}

	@Override
	public Entity transJSON(JSONObject obj) throws JSONException,
			ParseException {
		this.setId(obj.getInt("id"));
		this.setContent(obj.getString("content"));
		this.setActivityID(obj.getInt("ActivityID"));
		try {
			this.setDatatime(new SimpleDateFormat("yyyy-MM-dd HH:mm:ss")
					.parse(obj.getString("datetime")));
		} catch (NullPointerException e) {
			Log.e("CP Error", e.getMessage());
			Log.w("CP Exception", Log.getStackTraceString(e));
		} catch (IllegalArgumentException e) {
			Log.e("CP Error", e.getMessage());
			Log.w("CP Exception", Log.getStackTraceString(e));
		}
		this.setPictureUrl(obj.getString("picture_url"));
		return this;
	}

}
