package net.templefox.database.data;

import java.text.ParseException;

import org.json.JSONException;
import org.json.JSONObject;

import android.content.ContentValues;

// Generated 2013-8-21 19:58:16 by Hibernate Tools 3.4.0.CR1



/**
 * Location generated by hbm2java
 */
public class Location extends Entity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1099126998532756928L;
	private Integer id;
	private String name;
	private String detail;
	private String pictureUrl;
	private String address;

	public Location() {
	}

	public Location(String name, String address) {
		this.name = name;
		this.address = address;
	}

	public Location(String name, String detail, String pictureUrl,
			String address) {
		this.name = name;
		this.detail = detail;
		this.pictureUrl = pictureUrl;
		this.address = address;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public String getPictureUrl() {
		return this.pictureUrl;
	}

	public void setPictureUrl(String pictureUrl) {
		this.pictureUrl = pictureUrl;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Override
	public ContentValues getContentValues() throws IllegalArgumentException,
			NullPointerException {
		ContentValues value = new ContentValues();
		value.put("name", name);
		value.put("id", id);
		return value;
	}

	@Override
	public String getTableName() {
		return "location";
	}

	@Override
	public Entity resolveJSON(JSONObject obj) throws JSONException,
			ParseException {
		this.setId(obj.getInt("id"));
		this.setName(obj.getString("name"));
		return this;
	}

}
