package net.templefox.database.data;

// Generated 2013-8-21 19:58:16 by Hibernate Tools 3.4.0.CR1

import java.text.DateFormat;
import java.text.ParseException;
import java.util.Date;
import org.json.JSONException;
import org.json.JSONObject;

import com.google.gson.JsonObject;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private static final long serialVersionUID = -4497016747707135215L;
	private Integer id;
	private Integer location;
	private String name;
	private Date reg_time;
	private String phoneNum;
	private String email;
	private int authority;
	private String password;
	public static final int AUTHORITY_UNCHECK = 3;
	public static final int AUTHORITY_CHECKED = 2;
	public static final int AUTHORITY_AUTHORIZED = 1;
	public static final int AUTHORITY_ULTIMATED = 0;
	
	public User() {
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getLocation() {
		return this.location;
	}

	public void setLocation(Integer location) {
		this.location = location;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getRegTime() {
		return this.reg_time;
	}

	public void setRegTime(Date regTime) {
		this.reg_time = regTime;
	}

	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public String getEMail() {
		return this.email;
	}

	public void setEMail(String EMail) {
		this.email = EMail;
	}

	public int getAuthority() {
		return this.authority;
	}

	public void setAuthority(int authority) {
		this.authority = authority;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public User transJSON(JsonObject obj) {
		User user = this;
		user.setId(obj.get("id_user").getAsInt());
		user.setName(obj.get("name").getAsString());
		user.setEMail(obj.get("email").getAsString());
		user.setAuthority(obj.get("authority").getAsInt());
		try {
			user.setRegTime(DateFormat.getDateInstance().parse(obj.get("reg_time").getAsString()));
		} catch (ParseException e) {
			e.printStackTrace();
		}
		return user;
	}

	
}
