package com.example.iyangpu.data;

// Generated 2013-8-21 19:58:16 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Activity generated by hbm2java
 */
public class Activity implements java.io.Serializable {

	private Integer id;
	private Integer user;
	private Integer location;
	private String name;
	private String address;
	private String content;
	private String type;
	private String theme;
	private Date data;
	private Date time;
	private String procedure;
	private String pictureUrl;
	private String reporterInfo;
	private Integer isAttention = 0;
	private Integer isRating = 0;
	private Float reporterRating = 0f;
	private Float staffRating = 0f;
	private Float contentRating = 0f;
	private Float environmentRating = 0f;
	private int temperature;
	private Set<Comment> comments = new HashSet<Comment>(0);
	private Set attentions = new HashSet(0);

	public Activity() {
	}

	public Activity(String name, String address, String type, int temperature) {
		this.name = name;
		this.address = address;
		this.type = type;
		this.temperature = temperature;
	}

	public Activity(int user, Integer location, String name, String address,
			String content, String type, String theme, Date data, Date time,
			String procedure, String pictureUrl, String reporterInfo,
			int temperature, Set comments, Set attentions) {
		this.user = user;
		this.location = location;
		this.name = name;
		this.address = address;
		this.content = content;
		this.type = type;
		this.theme = theme;
		this.data = data;
		this.time = time;
		this.procedure = procedure;
		this.pictureUrl = pictureUrl;
		this.reporterInfo = reporterInfo;
		this.temperature = temperature;
		this.comments = comments;
		this.attentions = attentions;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getUser() {
		return this.user;
	}

	public void setUser(int user) {
		this.user = user;
	}

	public Integer getLocation() {
		return this.location;
	}

	public void setLocation(Integer location) {
		this.location = location;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	public Date getDate() {
		return this.data;
	}

	public void setDate(Date data) {
		this.data = data;
	}

	public Date getTime() {
		return this.time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public String getProcedure() {
		return this.procedure;
	}

	public void setProcedure(String procedure) {
		this.procedure = procedure;
	}

	public String getPictureUrl() {
		return this.pictureUrl;
	}

	public void setPictureUrl(String pictureUrl) {
		this.pictureUrl = pictureUrl;
	}

	public String getReporterInfo() {
		return this.reporterInfo;
	}

	public void setReporterInfo(String reporterInfo) {
		this.reporterInfo = reporterInfo;
	}

	public int getTemperature() {
		return this.temperature;
	}

	public void setTemperature(int temperature) {
		this.temperature = temperature;
	}

	public Set<Comment> getComments() {
		return this.comments;
	}

	public void setComments(Set<Comment> comments) {
		this.comments = comments;
	}

	public Set getAttentions() {
		return this.attentions;
	}

	public void setAttentions(Set attentions) {
		this.attentions = attentions;
	}
	
	public Integer getisAttention() {
		return this.isAttention;
	}
	
	public void setisAttention(int i) {
		isAttention = i;
	}
	public Float getReporterRating() {
		return this.reporterRating;
	}

	public void setReporterRating(Float reporterRating) {
		this.reporterRating = reporterRating;
	}

	public Float getStaffRating() {
		return this.staffRating;
	}

	public void setStaffRating(Float staffRating) {
		this.staffRating = staffRating;
	}

	public Float getContentRating() {
		return this.contentRating;
	}

	public void setContentRating(Float contentRating) {
		this.contentRating = contentRating;
	}

	public Float getEnvironmentRating() {
		return this.environmentRating;
	}

	public void setEnvironmentRating(Float environmentRating) {
		this.environmentRating = environmentRating;
	}
	
	
	public Integer getIsRating() {
		return this.isRating;
	}

	public void setIsRating(Integer isRating) {
		this.isRating = isRating;
	}
	
	@Override
	public boolean equals(Object o) {
		Activity be = (Activity) o;
		return be.id == this.id;
	}

	@Override
	public int hashCode() {
		return 1;
		//在Set中去除重复，只要判断主码即可。
	}
	
	
}
