package com.example.database.data;

import java.text.ParseException;

import org.json.JSONException;
import org.json.JSONObject;

import android.content.ContentValues;

// Generated 2013-8-21 19:58:16 by Hibernate Tools 3.4.0.CR1

/**
 * Attention generated by hbm2java
 */
public class Attention extends Entity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6716713138451809345L;
	private Integer id;
	private Integer activityID;
	private Integer userID;
	private Boolean isPresent;
	private Boolean isRating;
	private Integer contentRating;
	private Integer reporterRating;
	private Integer staffRating;
	private Integer environmentRating;
	
	public Attention() {
	}

	public Attention(Integer activityID, Integer userID, Boolean isPresent) {
		this.activityID = activityID;
		this.userID = userID;
		this.isPresent = isPresent;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getactivityID() {
		return this.activityID;
	}

	public void setActivityID(Integer activityID) {
		this.activityID = activityID;
	}

	public Integer getUser() {
		return this.userID;
	}

	public void setUser(Integer user) {
		this.userID = user;
	}

	public Boolean getIsPresent() {
		return this.isPresent;
	}

	public void setIsPresent(Boolean isPresent) {
		this.isPresent = isPresent;
	}
	public Boolean getIsRating() {
		return this.isRating;
	}

	public void setIsRating(Boolean isRating) {
		this.isRating = isRating;
	}

	public Integer getContentRating() {
		return this.contentRating;
	}

	public void setContentRating(Integer contentRating) {
		this.contentRating = contentRating;
	}

	public Integer getReporterRating() {
		return this.reporterRating;
	}

	public void setReporterRating(Integer reporterRating) {
		this.reporterRating = reporterRating;
	}

	public Integer getStaffRating() {
		return this.staffRating;
	}

	public void setStaffRating(Integer staffRating) {
		this.staffRating = staffRating;
	}

	public Integer getEnvironmentRating() {
		return this.environmentRating;
	}

	public void setEnvironmentRating(Integer environmentRating) {
		this.environmentRating = environmentRating;
	}

	@Override
	public boolean equals(Object o) {
		// TODO Auto-generated method stub
		Attention oo = (Attention) o;
		return id == oo.id;
	}

	@Override
	public int hashCode() {
		// TODO Auto-generated method stub
		return id;
	}

	@Override
	protected ContentValues getContentValues() {
		ContentValues value = new ContentValues();
		value.put("id", id);
		value.put("isPresent", isPresent);
		value.put("userID", userID);
		value.put("activityID", activityID);
		value.put("isRating", isRating);
		return value;
	}

	@Override
	protected String getTableName() {
		// TODO Auto-generated method stub
		return "attention";
	}

	@Override
	public Entity transJSON(JSONObject obj) throws JSONException,
			ParseException {
		this.setId(obj.getInt("id"));
		this.setIsPresent(obj.getInt("isPresent")==1?true:false);
		this.setUser(obj.getInt("UserID"));
		this.setActivityID(obj.getInt("ActivityID"));
		this.setIsRating(obj.getInt("isRating")==1?true:false);
		
		return this;
	}

}
