package com.example.database.data;

// Generated 2013-8-21 19:58:16 by Hibernate Tools 3.4.0.CR1

/**
 * Attention generated by hbm2java
 */
public class Attention implements java.io.Serializable {

	private Integer id;
	private Activity activity;
	private User user;
	private Boolean isPresent;
	private Boolean isRating;
	private Integer contentRating;
	private Integer reporterRating;
	private Integer staffRating;
	private Integer environmentRating;
	
	public Attention() {
	}

	public Attention(Activity activity, User user, Boolean isPresent) {
		this.activity = activity;
		this.user = user;
		this.isPresent = isPresent;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Activity getActivity() {
		return this.activity;
	}

	public void setActivity(Activity activity) {
		this.activity = activity;
	}

	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public Boolean getIsPresent() {
		return this.isPresent;
	}

	public void setIsPresent(Boolean isPresent) {
		this.isPresent = isPresent;
	}
	public Boolean getIsRating() {
		return this.isRating;
	}

	public void setIsRating(Boolean isRating) {
		this.isRating = isRating;
	}

	public Integer getContentRating() {
		return this.contentRating;
	}

	public void setContentRating(Integer contentRating) {
		this.contentRating = contentRating;
	}

	public Integer getReporterRating() {
		return this.reporterRating;
	}

	public void setReporterRating(Integer reporterRating) {
		this.reporterRating = reporterRating;
	}

	public Integer getStaffRating() {
		return this.staffRating;
	}

	public void setStaffRating(Integer staffRating) {
		this.staffRating = staffRating;
	}

	public Integer getEnvironmentRating() {
		return this.environmentRating;
	}

	public void setEnvironmentRating(Integer environmentRating) {
		this.environmentRating = environmentRating;
	}
}
