package com.example.database.data;

// Generated 2013-8-21 19:58:16 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 */
public class Location implements java.io.Serializable {

	private Integer id;
	private String name;
	private String detail;
	private String pictureUrl;
	private String address;
	private Set users = new HashSet(0);
	private Set activities = new HashSet(0);

	public Location() {
	}

	public Location(String name, String address) {
		this.name = name;
		this.address = address;
	}

	public Location(String name, String detail, String pictureUrl,
			String address, Set users, Set activities) {
		this.name = name;
		this.detail = detail;
		this.pictureUrl = pictureUrl;
		this.address = address;
		this.users = users;
		this.activities = activities;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDetail() {
		return this.detail;
	}

	public void setDetail(String detail) {
		this.detail = detail;
	}

	public String getPictureUrl() {
		return this.pictureUrl;
	}

	public void setPictureUrl(String pictureUrl) {
		this.pictureUrl = pictureUrl;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public Set getUsers() {
		return this.users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}

	public Set getActivities() {
		return this.activities;
	}

	public void setActivities(Set activities) {
		this.activities = activities;
	}

}
