package com.example.database.data;

// Generated 2013-8-21 19:58:16 by Hibernate Tools 3.4.0.CR1

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import org.json.JSONException;
import org.json.JSONObject;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer id;
	private Location location;
	private String name;
	private Date regTime;
	private String phoneNum;
	private String EMail;
	private int authority;
	private String password;
	private Set attentions = new HashSet(0);
	private Set comments = new HashSet(0);
	private Set activities = new HashSet(0);

	public User() {
	}

	public User(String nickname, Date regTime,
			int authority, String password) {
		this.name = nickname;
		this.regTime = regTime;
		this.authority = authority;
		this.password = password;
	}

	public User(Location location, String nickname,
			Date regTime, String phoneNum, String EMail, int authority,
			String password, Set attentions, Set comments, Set activities) {
		this.location = location;
		this.name = nickname;
		this.regTime = regTime;
		this.phoneNum = phoneNum;
		this.EMail = EMail;
		this.authority = authority;
		this.password = password;
		this.attentions = attentions;
		this.comments = comments;
		this.activities = activities;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}



	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getRegTime() {
		return this.regTime;
	}

	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}

	public String getPhoneNum() {
		return this.phoneNum;
	}

	public void setPhoneNum(String phoneNum) {
		this.phoneNum = phoneNum;
	}

	public String getEMail() {
		return this.EMail;
	}

	public void setEMail(String EMail) {
		this.EMail = EMail;
	}

	public int isAuthority() {
		return this.authority;
	}

	public void setAuthority(int authority) {
		this.authority = authority;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set getAttentions() {
		return this.attentions;
	}

	public void setAttentions(Set attentions) {
		this.attentions = attentions;
	}

	public Set getComments() {
		return this.comments;
	}

	public void setComments(Set comments) {
		this.comments = comments;
	}

	public Set<Activity> getActivities() {
		return this.activities;
	}

	public void setActivities(Set activities) {
		this.activities = activities;
	}

	public User transJSON(JSONObject obj)
			throws JSONException, ParseException {
		User user = this;
		user.setId(obj.getInt("id"));
		user.setName(obj.getString("name"));
		user.setEMail(obj.getString("E_mail"));
		user.setPhoneNum(obj.getString("phone_num"));
		user.setRegTime(SimpleDateFormat.getDateInstance().parse(obj.getString("reg_time")));
		user.setAuthority(obj.getInt("authority"));
		return user;
	}

	
}
